import Head from 'next/head'
import Database from "@/lib/Database";
import Post from "@/models/Post";
import NewsList from "@/components/NewsList";

export async function getServerSideProps(context: any) {
    await Database.connect();
    const posts = await Post.find().sort({id:"desc"}).limit(10);
    let pArr = JSON.parse(JSON.stringify(posts));
    return {
        props: {data:pArr},
    };
}

export default function Home({data}: any) {

    return (
        <>
            <Head>
                <title>BeeNews</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <NewsList data={data} />
        </>
    )
}
